# Generated by Django 4.0.3 on 2022-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatedAt',
            field=models.DateField(auto_now_add=True, verbose_name='Data de atualização'),
        ),
    ]
